# ZDS Documentation Site
title: Zippy
description: A human-readable, schema-flexible document store for modern data workflows
url: "https://zippydata.org"
baseurl: ""
logo: "/assets/images/z.png"

# Theme
theme: just-the-docs
color_scheme: zippy

# Repository
github_username: zippydata
repository: zippydata/zippy

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
nav_enabled: true
nav_sort: case_sensitive

# Footer
footer_content: '© 2024 MIT License · <a href="https://omarkamali.com">Omar Kamali</a>'

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/zippydata/zippy"
aux_links_new_tab: true

# External nav links
nav_external_links:
  - title: Technical Paper
    url: https://github.com/zippydata/zippy/blob/master/PAPER.md
    hide_icon: false

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      nav_order: 1

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
